version: "3.1"

# Language and pipeline configuration
language: id  # Indonesian language

pipeline:
  # Tokenizer for Indonesian
  - name: WhitespaceTokenizer
  
  # RegexFeaturizer for pattern matching
  - name: RegexFeaturizer
  
  # Lexical Syntactic Featurizer
  - name: LexicalSyntacticFeaturizer
  
  # Count Vectors Featurizer for word frequency
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  
  # Another Count Vectors for word-level features
  - name: CountVectorsFeaturizer
  
  # DIETClassifier for intent classification and entity extraction
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    # Use softmax for confidence calculation
    model_confidence: softmax
  
  # FallbackClassifier with lower threshold
  - name: FallbackClassifier
    threshold: 0.7  # Lowered from default 0.8
    ambiguity_threshold: 0.1

# Policy configuration
policies:
  # RulePolicy for deterministic rules
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_default_fallback
  
  # MemoizationPolicy for exact story matches
  - name: MemoizationPolicy
    max_history: 5
  
  # TEDPolicy for story prediction
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    # Use softmax for confidence calculation
    model_confidence: softmax

# Assistant configuration
assistant_id: bri_banking_chatbot